# Site settings
title: "MengQi Lei"
description: "MengQi Lei's Personal Website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    MengQi Lei<br> <br><strong><em>Software Engineer & Game Developer</em></strong>
resume_title:                   "<strong>About me</strong>"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "lisasimpson@youremailaddress.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: > 
  <p>Hi! I am MengQi Lei, a passionate software engineer, game developer and full-time student at University of Illinois Urbana-Champaign. I'm currently persuing Master of Computer Science degree with expected graduation date of May 2027. Additionally, I graduated with Bachelor of Science in Computer Science & Engineering at The Ohio State University on May 2025.</p>

  <p> During my time at Ohio State, I have served as a <b>Teaching Assistant</b> for a junior/senior-level computer animation and video games class at The Ohio State University (CSE3541/5541). In this role, I had the privilege of assisting over 180 students with their Unity and C# projects, helping them clarify technical concepts and debug issues. I also facilitated communication between students and teaching staff, which strengthened collaboration within the course. This experience allowed me to not only deepen my own understanding of core concepts but also to help others on their learning journey, a rewarding experience that complements my technical skills.</p>

  <p> In addition, During my time as a <b>PC Game Developer Intern</b> at Resilience, Inc., I was able to turn creative visions into reality by designing and implementing 2D and 3D gameplay systems using Unity and C#. My work included developing player controls, physics interactions, and UI features, all with the goal of enhancing the overall user experience. This role was a great opportunity to apply my skills in an agile environment, where I collaborated with a cross-functional team of eight developers to deliver high-quality code through version control and peer reviews, ultimately accelerating our feature delivery and reducing bug resolution time.</p>

  <p> I have a wide range of interests that covers <strong>game development, artificial intelligence, full-stack development, and mobile development</strong>. I also have experience with several coding languages including but not limited to Java, Python, C#, C++ and C. With my experience and skills, I'm looking for an internship oppurtunity for Summer and Fall 2026 to further develop my skills and contribute to the industry with my passion.</p>

  <p> I am also a lifelong aviation geek. I'm obsessed with civil aviation for as long as I can remember. Besides everything about plane, I also enjoy soccer very much, both playing and watching.</p>

  <p> Feel free to connect with me on LinkedIn, check out my resume, and if you also like aviation, make sure to take a look at my YouTube channel! I'm eager to enbrace wherever my interests and skills take me on my journey as a software engineer and aviation enthusiast.</p>

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       false
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/MqLei423"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mengqi-lei/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
